ALTER TABLE Client ADD COLUMN active BOOLEAN DEFAULT TRUE;
ALTER TABLE Assistant ADD COLUMN active BOOLEAN DEFAULT TRUE;
ALTER TABLE Agent ADD COLUMN active BOOLEAN DEFAULT TRUE;
ALTER TABLE Administrateur ADD COLUMN active BOOLEAN DEFAULT TRUE;
